#! /bin/bash

#BSUB -L /bin/bash
#BSUB -q large
#BSUB -n 20 -W 48:00
#BSUB -J Singletrome
#BSUB -o Singletrome.out
#BSUB -e Singletrome.err
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=10G]

module load apptainer/1.3.5

apptainer exec ./singletrome_apptainer_cellranger602.sif  python Singletrome.py --mkref=T -o output_test7

apptainer exec ./singletrome_apptainer_cellranger602.sif python CreateBedFilesForGTF.py --pathToGTF  output_test7/singletrome.gtf --outDir output_test7

apptainer exec ./singletrome_apptainer_cellranger602.sif python run_cellranger.py Cellranger_count_input.txt /home/zixiu.li-umw/Singletrome/output_test7/Singletrome_Genome_index
